# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-16 21:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bit_Clicker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_game_status',
            old_name='user',
            new_name='the_user',
        ),
    ]
