# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-17 05:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bit_Clicker', '0002_auto_20161116_2139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_game_status',
            old_name='doube_upgrades_owned',
            new_name='double_upgrades_owned',
        ),
    ]
